### ISSUE TITLE
java.lang.Exception: Command [class_file:/tmp/class/a.class] not supported

### ISSUE THREAD

**Issue by TheCryingGame** [woodpecker-framework/ysoserial-for-woodpecker#14]
java -jar ysoserial-for-woodpecker-0.5.2.jar -g CommonsCollections5 -a "class_file:/tmp/class/a.class"
Error while generating or serializing payload
java.lang.Exception: Command [class_file:/tmp/class/a.class] not supported
        at me.gv7.woodpecker.yso.payloads.custom.CommonsCollectionsUtil.getTransformerList(CommonsCollectionsUtil.java:206)
        at me.gv7.woodpecker.yso.payloads.CommonsCollections5.getObject(CommonsCollections5.java:61)
        at me.gv7.woodpecker.yso.payloads.CommonsCollections5.getObject(CommonsCollections5.java:49)
        at me.gv7.woodpecker.yso.GeneratePayload.main(GeneratePayload.java:65)

**Comment by c0ny1** [comment]
报错是正常的，cc5没有class_file，要执行代码可以尝试bcel_class_file或script

**Comment by TheCryingGame** [comment]
> 报错是正常的，cc5没有class_file，要执行代码可以尝试bcel_class_file或script

师傅是整个cc链没有class_file还是只有单独的几个才有，能标注出来吗

**Comment by c0ny1** [comment]
是部分cc链没有，这个目前还没有想好如何标注，只能运行看，不支持就会提示not supported。

**Comment by TheCryingGame** [comment]
> 是部分cc链没有，这个目前还没有想好如何标注，只能运行看，不支持就会提示not supported。

明白了，希望师傅以后能完善QAQ
