### ISSUE TITLE
指定class_file的问题

### ISSUE THREAD

**Issue by rv0p111** [woodpecker-framework/ysoserial-for-woodpecker#4]
Error while generating or serializing payload
javassist.NotFoundException: T1610459859155834
	at javassist.ClassPool.get(ClassPool.java:450)
	at javassist.ClassPool.getCtClass(ClassPool.java:515)
	at me.gv7.woodpecker.yso.payloads.util.Gadgets.createTemplatesImpl(Gadgets.java:132)
	at me.gv7.woodpecker.yso.payloads.util.Gadgets.createTemplatesImpl(Gadgets.java:83)
	at me.gv7.woodpecker.yso.payloads.CommonsBeanutils2_183.getObject(CommonsBeanutils2_183.java:26)
	at me.gv7.woodpecker.yso.GeneratePayload.main(GeneratePayload.java:65)

**Comment by c0ny1** [comment]
问题已经解决 请下载[0.5.0](https://github.com/woodpecker-framework/ysoserial-for-woodpecker/releases/tag/0.5.0)版本

**Comment by 4rat** [comment]
java -jar ysoserial-for-woodpecker-0.5.1.jar -g CommonsBeanutils1 -a "raw_cmd:calc.exe"

Error while generating or serializing payload
java.lang.IllegalAccessError: class me.gv7.woodpecker.yso.payloads.util.Gadgets (in unnamed module @0x3c60b7e7) cannot access class com.sun.org.apache.xalan.internal.xsltc.trax.TemplatesImpl (in module java.xml) because module java.xml does not export com.sun.org.apache.xalan.internal.xsltc.trax to unnamed module @0x3c60b7e7
	at me.gv7.woodpecker.yso.payloads.util.Gadgets.createTemplatesImpl(Gadgets.java:77)
	at me.gv7.woodpecker.yso.payloads.CommonsBeanutils1.getObject(CommonsBeanutils1.java:20)
	at me.gv7.woodpecker.yso.GeneratePayload.main(GeneratePayload.java:65)

**Comment by 4rat** [comment]
java version "17.0.3.1" 2022-04-22 LTS
java -jar ysoserial-for-woodpecker-0.5.1.jar -g CommonsBeanutils1 -a "raw_cmd:calc.exe"

Error while generating or serializing payload
java.lang.IllegalAccessError: class me.gv7.woodpecker.yso.payloads.util.Gadgets (in unnamed module @0x3c60b7e7) cannot access class com.sun.org.apache.xalan.internal.xsltc.trax.TemplatesImpl (in module java.xml) because module java.xml does not export com.sun.org.apache.xalan.internal.xsltc.trax to unnamed module @0x3c60b7e7
at me.gv7.woodpecker.yso.payloads.util.Gadgets.createTemplatesImpl(Gadgets.java:77)
at me.gv7.woodpecker.yso.payloads.CommonsBeanutils1.getObject(CommonsBeanutils1.java:20)
at me.gv7.woodpecker.yso.GeneratePayload.main(GeneratePayload.java:65)
